# Site settings
title: Change I Can Digest
email: opleban@gmail.com
description: "The personal website for OJP."
baseurl: ""
url: ""
twitter_username: opleban
github_username:  opleban
linkedIn_profile: https://www.linkedin.com/pub/ori-pleban/1a/790/67a 

# Build settings
markdown: kramdown
permalink: pretty
