# Site settings
title: Change I Can Digest
email: opleban@gmail.com
description: "The personal website for OJP."
baseurl: ""
url: ""
twitter_username: opleban
github_username:  opleban
linkedIn_profile: https://www.linkedin.com/in/opleban/
analytics:
  provider: google
  google:
    tracking_id: 'UA-55077403-1'
getclicky :
    site_id :
# Build settings
markdown: kramdown
permalink: pretty
